export const PRODUCTS_DATA_FAILURE = "PRODUCTS/DATA/FAILURE";
export const PRODUCTS_DATA_REQUEST = "PRODUCTS/DATA/REQUEST";
export const PRODUCTS_DATA_SUCCESS = "PRODUCTS/DATA/SUCCESS";
export const SEARCH_PRODUCT_ID = "SEARCH/PRODUCT/ID";
